# Generated by Django 6.0 on 2025-12-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Text to display, e.g., 'Flash Sale! 50% Off Everything'", max_length=100)),
                ('ends_at', models.DateTimeField(help_text='When the countdown timer should stop')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this banner immediately')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
