# Generated by Django 6.0 on 2025-12-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_salebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's name", max_length=100)),
                ('location', models.CharField(help_text='City or Region (e.g., Mumbai)', max_length=100)),
                ('text', models.TextField(help_text='The review content')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Star rating (1-5)')),
                ('product_name', models.CharField(help_text='Name of the product they purchased', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional customer photo', null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
