# Generated by Django 6.0 on 2025-12-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_faqcategory_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeGuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="e.g., 'rings', 'bracelets'", unique=True)),
                ('name', models.CharField(help_text="Display name e.g., 'Ring Size Chart'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('columns', models.JSONField(default=list, help_text='List of column headers')),
                ('data', models.JSONField(default=list, help_text='List of row objects')),
                ('instruction_title', models.CharField(blank=True, default='How to Measure', max_length=200)),
                ('instruction_text', models.TextField(blank=True, help_text='Steps or description for measuring')),
            ],
            options={
                'verbose_name_plural': 'Size Guide Categories',
                'ordering': ['order'],
            },
        ),
    ]
