# Generated by Django 6.0 on 2025-12-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sizeguidecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeguidecategory',
            name='columns',
            field=models.JSONField(default=list, help_text="List of column headers ex: ['Indian Size', 'US Size', 'UK Size', 'Diameter (mm)']"),
        ),
        migrations.AlterField(
            model_name='sizeguidecategory',
            name='data',
            field=models.JSONField(default=list, help_text="List of row objects ex: [{'Indian Size': '6', 'US Size': '3', 'UK Size': '14.1', 'Diameter (mm)':'14.1'}, ...]"),
        ),
    ]
